### ISSUE TITLE
[WCFM Migrator]: Several Issues & enhancements

### ISSUE THREAD

**Issue by shashwatahalder01** [getdokan/dokan-migrator#11]
- [ ] Scenario 1:  Migrate to Dokan option should be closeable. After closing there should alert/message from
 where the migrator option can be accessed again.

- [ ] Scenario 2: 
Dokan migration should also be accessible from the dokan get help dropdown. Implement migrator option on dokan get help dropdown

- [x] Scenario 3:
Fatal error for [below special scenario] migrating  :

Steps: 
1. Enable dokan  & place order
2. Install dokan migrator & WCFM plugins
3. go to migrator panel [doken order exits on migrator list, shouldn't be
4. Fatal error for running migrator

Fatal Error:
[15-May-2023 05:46:26 UTC] PHP Fatal error:  Uncaught Error: Call to a member function format() on bool in /Users/rk/Sites/Dokan2/wp-content/plugins/dokan-migrator/includes/Abstracts/OrderMigration.php:226
Stack trace:
#0 /Users/rk/Sites/Dokan2/wp-content/plugins/dokan-migrator/includes/Abstracts/OrderMigration.php(272): WeDevs\DokanMigrator\Abstracts\OrderMigration->sync_dokan_order_table(Array, 23, 2, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /Users/rk/Sites/Dokan2/wp-content/plugins/dokan-migrator/includes/Migrator/Manager.php(181): WeDevs\DokanMigrator\Abstracts\OrderMigration->process_migration()
#2 /Users/rk/Sites/Dokan2/wp-content/plugins/dokan-migrator/includes/Migrator/Ajax.php(90): WeDevs\DokanMigrator\Migrator\Manager->migrate('order', 'wcfmmarketplace', Array)
#3 /Users/rk/Sites/Dokan2/wp-includes/class-wp-hook.php(308): WeDevs\DokanMigrator\Migrator\Ajax->import('')
#4 /Users/rk/Sites/Dokan2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#5 /Users/rk/Sites/Dokan2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /Users/rk/Sites/Dokan2/wp-admin/admin-ajax.php(188): do_action('wp_ajax_dokan_m...')
#7 /Users/rk/.composer/vendor/laravel/valet/server.php(234): require('/Users/rk/Sites...')
#8 {main}
  thrown in /Users/rk/Sites/Dokan2/wp-content/plugins/dokan-migrator/includes/Abstracts/OrderMigration.php on line 226

**Comment by mohtasimbillahrafi** [comment]
I want to migrate from WCFM to Dokan transfer but it’s not happening
